// 40종 동물 캐릭터 (이모지 기반이라 별도 이미지 리소스 없이 바로 동작합니다)
const ANIMALS = [
  { id: 1,  name: '사자',   emoji: '🦁' },
  { id: 2,  name: '호랑이', emoji: '🐯' },
  { id: 3,  name: '곰',     emoji: '🐻' },
  { id: 4,  name: '판다',   emoji: '🐼' },
  { id: 5,  name: '코알라', emoji: '🐨' },
  { id: 6,  name: '여우',   emoji: '🦊' },
  { id: 7,  name: '늑대',   emoji: '🐺' },
  { id: 8,  name: '토끼',   emoji: '🐰' },
  { id: 9,  name: '고양이', emoji: '🐱' },
  { id: 10, name: '강아지', emoji: '🐶' },
  { id: 11, name: '생쥐',   emoji: '🐭' },
  { id: 12, name: '햄스터', emoji: '🐹' },
  { id: 13, name: '소',     emoji: '🐮' },
  { id: 14, name: '돼지',   emoji: '🐷' },
  { id: 15, name: '원숭이', emoji: '🐵' },
  { id: 16, name: '고릴라', emoji: '🦍' },
  { id: 17, name: '코끼리', emoji: '🐘' },
  { id: 18, name: '코뿔소', emoji: '🦏' },
  { id: 19, name: '하마',   emoji: '🦛' },
  { id: 20, name: '낙타',   emoji: '🐫' },
  { id: 21, name: '기린',   emoji: '🦒' },
  { id: 22, name: '얼룩말', emoji: '🦓' },
  { id: 23, name: '사슴',   emoji: '🦌' },
  { id: 24, name: '말',     emoji: '🐴' },
  { id: 25, name: '유니콘', emoji: '🦄' },
  { id: 26, name: '닭',     emoji: '🐔' },
  { id: 27, name: '펭귄',   emoji: '🐧' },
  { id: 28, name: '병아리', emoji: '🐤' },
  { id: 29, name: '독수리', emoji: '🦅' },
  { id: 30, name: '부엉이', emoji: '🦉' },
  { id: 31, name: '박쥐',   emoji: '🦇' },
  { id: 32, name: '개구리', emoji: '🐸' },
  { id: 33, name: '거북이', emoji: '🐢' },
  { id: 34, name: '뱀',     emoji: '🐍' },
  { id: 35, name: '악어',   emoji: '🐊' },
  { id: 36, name: '고래',   emoji: '🐳' },
  { id: 37, name: '돌고래', emoji: '🐬' },
  { id: 38, name: '문어',   emoji: '🐙' },
  { id: 39, name: '상어',   emoji: '🦈' },
  { id: 40, name: '나비',   emoji: '🦋' },
];

module.exports = { ANIMALS };
