// 40종 동물 캐릭터 (이모지 기반이라 별도 이미지 리소스 없이 바로 동작합니다)
const ANIMALS = [
  { id: 1,  name: '사자',   emoji: '🦁' },
  { id: 2,  name: '호랑이', emoji: '🐯' },
  { id: 3,  name: '곰',     emoji: '🐻' },
  { id: 4,  name: '판다',   emoji: '🐼' },
  { id: 5,  name: '코알라', emoji: '🐨' },
  { id: 6,  name: '여우',   emoji: '🦊' },
  { id: 7,  name: '늑대',   emoji: '🐺' },
  { id: 8,  name: '토끼',   emoji: '🐰' },
  { id: 9,  name: '고양이', emoji: '🐱' },
  { id: 10, name: '강아지', emoji: '🐶' },
  { id: 11, name: '생쥐',   emoji: '🐭' },
  { id: 12, name: '햄스터', emoji: '🐹' },
  { id: 13, name: '소',     emoji: '🐮' },
  { id: 14, name: '돼지',   emoji: '🐷' },
  { id: 15, name: '원숭이', emoji: '🐵' },
  { id: 16, name: '고릴라', emoji: '🦍' },
  { id: 17, name: '코끼리', emoji: '🐘' },
  { id: 18, name: '코뿔소', emoji: '🦏' },
  { id: 19, name: '하마',   emoji: '🦛' },
  { id: 20, name: '낙타',   emoji: '🐫' },
  { id: 21, name: '기린',   emoji: '🦒' },
  { id: 22, name: '얼룩말', emoji: '🦓' },
  { id: 23, name: '사슴',   emoji: '🦌' },
  { id: 24, name: '말',     emoji: '🐴' },
  { id: 25, name: '유니콘', emoji: '🦄' },
  { id: 26, name: '닭',     emoji: '🐔' },
  { id: 27, name: '펭귄',   emoji: '🐧' },
  { id: 28, name: '병아리', emoji: '🐤' },
  { id: 29, name: '독수리', emoji: '🦅' },
  { id: 30, name: '부엉이', emoji: '🦉' },
  { id: 31, name: '박쥐',   emoji: '🦇' },
  { id: 32, name: '개구리', emoji: '🐸' },
  { id: 33, name: '거북이', emoji: '🐢' },
  { id: 34, name: '뱀',     emoji: '🐍' },
  { id: 35, name: '악어',   emoji: '🐊' },
  { id: 36, name: '고래',   emoji: '🐳' },
  { id: 37, name: '돌고래', emoji: '🐬' },
  { id: 38, name: '문어',   emoji: '🐙' },
  { id: 39, name: '상어',   emoji: '🦈' },
  { id: 40, name: '나비',   emoji: '🦋' },

  
  { id: 41, name: '벌', emoji: '🐝' },
  { id: 42, name: '애벌레', emoji: '🐛' },
  { id: 43, name: '무당벌레', emoji: '🐞' },
  { id: 44, name: '개미', emoji: '🐜' },
  { id: 45, name: '귀뚜라미', emoji: '🦗' },
  { id: 46, name: '거미', emoji: '🕷️' },
  { id: 47, name: '전갈', emoji: '🦂' },
  { id: 48, name: '새우', emoji: '🦐' },
  { id: 49, name: '게', emoji: '🦀' },
  { id: 50, name: '가재', emoji: '🦞' },

  { id: 51, name: '오징어', emoji: '🦑' },
  { id: 52, name: '물고기', emoji: '🐟' },
  { id: 53, name: '열대어', emoji: '🐠' },
  { id: 54, name: '복어', emoji: '🐡' },
  { id: 55, name: '고래2', emoji: '🐋' },
  { id: 56, name: '바다표범', emoji: '🦭' },
  { id: 57, name: '도마뱀', emoji: '🦎' },
  { id: 58, name: '티라노사우루스', emoji: '🦖' },
  { id: 59, name: '브라키오사우루스', emoji: '🦕' },
  { id: 60, name: '용', emoji: '🐉' },

  { id: 61, name: '들소', emoji: '🦬' },
  { id: 62, name: '라마', emoji: '🦙' },
  { id: 63, name: '캥거루', emoji: '🦘' },
  { id: 64, name: '나무늘보', emoji: '🦥' },
  { id: 65, name: '수달', emoji: '🦦' },
  { id: 66, name: '비버', emoji: '🦫' },
  { id: 67, name: '스컹크', emoji: '🦨' },
  { id: 68, name: '오소리', emoji: '🦡' },
  { id: 69, name: '오랑우탄', emoji: '🦧' },
  { id: 70, name: '쥐', emoji: '🐁' },

  { id: 71, name: '큰쥐', emoji: '🐀' },
  { id: 72, name: '토끼2', emoji: '🐇' },
  { id: 73, name: '황소', emoji: '🐂' },
  { id: 74, name: '물소', emoji: '🐃' },
  { id: 75, name: '젖소', emoji: '🐄' },
  { id: 76, name: '멧돼지', emoji: '🐗' },
  { id: 77, name: '돼지2', emoji: '🐖' },
  { id: 78, name: '숫양', emoji: '🐏' },
  { id: 79, name: '양', emoji: '🐑' },
  { id: 80, name: '염소', emoji: '🐐' },

  { id: 81, name: '당나귀', emoji: '🫏' },
  { id: 82, name: '말2', emoji: '🐎' },
  { id: 83, name: '닭2', emoji: '🐓' },
  { id: 84, name: '칠면조', emoji: '🦃' },
  { id: 85, name: '오리', emoji: '🦆' },
  { id: 86, name: '거위', emoji: '🪿' },
  { id: 87, name: '공작새', emoji: '🦚' },
  { id: 88, name: '앵무새', emoji: '🦜' },
  { id: 89, name: '백조', emoji: '🦢' },
  { id: 90, name: '플라밍고', emoji: '🦩' },
  ];

module.exports = { ANIMALS };
